feat: upgrade to 2.7 and include services extras
modyo/modyo-widgets-template-vue pull request #105
Opened 2023-01-06 20:32 UTC by Giorgiosaud

also removing unnecesary codes

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact for existing widgets:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2023-01-09 14:29 UTC, abe-modyo requested changes
Duda sincera, este PR viene de traerse lo que esta en modyoservices- tal cual ?

2023-01-09 14:29 UTC, abe-modyo commented on test-report.xml
> +<?xml version="1.0" encoding="UTF-8"?>
es necesario versionar este?

2023-01-10 12:25 UTC, Giorgiosaud commented on .eslintrc.js
> +      "plugin:vue/essential",
Para alivianar la carga de desarrollo para ajustes cuando no tienen bien configurado el editor ya que contiene reglas que en algunos casos no aplican a actualizaciones futuras y entre versiones cambia por lo que salen ajustes de pr que solo contienen fixes de linter y son dolorosos para la revision real

2023-01-10 12:25 UTC, Giorgiosaud commented on .eslintrc.js
> +      "plugin:vue/essential",
lo que si cambie es required

2023-01-10 12:28 UTC, Giorgiosaud commented on .eslintrc.js
> +      "plugin:vue/essential",
recommended en vez de essentials porque vemos que tiene las suficientes reglas para el uso sin sobreescribir las que necesariamente sobreescribimos en el airbnb

2023-01-10 12:39 UTC, Giorgiosaud commented on .stylelintrc.json
> -{
lo cambiamos a stylelint.config.js deberiamos aprovechar de estandarizar los archivos config a algo comun pero siempre han sido cada uno distinto lo que se hizo en este caso fue cambiarlo para poder declarar las config como modulos

2023-01-10 12:40 UTC, Giorgiosaud commented on .validate-branch-namerc.json
> +{
en algunos casos los poc son mvp

2023-01-17 12:49 UTC, Giorgiosaud commented on test-report.xml
> +<?xml version="1.0" encoding="UTF-8"?>
lo saco ya esta el reporte de sonarCloud

2023-01-17 14:05 UTC, merged